name: CI

on:
  push:
    branches:
      - master
    pull_requuest:
      branches:
        - master

jobs:
  check:
    name: Build and test
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cxx_compiler: g++
          - compiler: clang
            cxx_compiler: clang++
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.cxx_compiler }}
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel clang cmake ninja extra-cmake-modules fmt libuv boost git qt6-base qt6-wayland libxkbcommon qt6-webengine lua opencc
      - uses: actions/checkout@v4
        with:
          repository: fcitx/fcitx5
          path: fcitx5
      - name: Cache fcitx5 data files
        uses: actions/cache@v4
        with:
          path: 'fcitx5/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('fcitx5/src/modules/spell/CMakeLists.txt') }}
      - name: Build and Install fcitx5
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5
          cmake-option: >-
            -DENABLE_KEYBOARD=Off
            -DENABLE_X11=Off
            -DENABLE_WAYLAND=Off
            -DENABLE_ENCHANT=Off
            -DENABLE_DBUS=Off
            -DENABLE_SERVER=Off
            -DENABLE_EMOJI=Off
            -DUSE_SYSTEMD=Off
      - uses: actions/checkout@v4
        with:
          repository: fcitx/libime
          path: libime
          submodules: true
      - name: Cache libime data files
        uses: actions/cache@v4
        with:
          path: 'libime/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('libime/data/CMakeLists.txt') }}
      - name: Build and Install libime
        uses: fcitx/github-actions@cmake
        with:
          path: libime
      - uses: actions/checkout@v4
        with:
          repository: fcitx/fcitx5-lua
          path: fcitx5-lua
      - name: Build and Install fcitx5-lua
        uses: fcitx/github-actions@cmake
        with:
          repository: fcitx/fcitx5-lua
          path: fcitx5-lua
      - uses: actions/checkout@v4
        with:
          repository: fcitx/fcitx5-qt
          path: fcitx5-qt
      - name: Build and Install fcitx5-qt
        uses: fcitx/github-actions@cmake
        with:
          repository: fcitx/fcitx5-qt
          path: fcitx5-qt
          cmake-option: >-
            -DENABLE_QT4=Off
            -DENABLE_QT5=Off
            -DENABLE_QT6=On
      - uses: actions/checkout@v4
        with:
          path: fcitx5-chinese-addons
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp
          source-root: fcitx5-chinese-addons
      - name: Build and Install fcitx5-chinese-addons
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5-chinese-addons
      - name: Test
        run: |
          ctest --test-dir fcitx5-chinese-addons/build
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
